#!/usr/bin/python3
def raise_exception():
    list = [1, 2, 3]
    a = 0
    b = a + list
